import polars as pl


def get_dtypes():
    return {'hosp/admissions': {'subject_id': pl.Int64,
                                'hadm_id': pl.Int64,
                                'admittime': pl.Datetime,
                                'dischtime': pl.Datetime,
                                'deathtime': pl.Datetime,
                                'admission_type': pl.Categorical,
                                'discharge_location': pl.Categorical,
                                'insurance': pl.Categorical,
                                'language': pl.Categorical,
                                'marital_status': pl.Categorical,
                                'race': pl.Categorical,
                                'edregtime': pl.Datetime,
                                'edouttime': pl.Datetime,
                                'hospital_expire_flag': pl.Int64},

            'hosp/patients': {'subject_id': pl.Int64,
                              'gender': pl.Utf8,
                              'anchor_age': pl.Int64,
                              'anchor_year': pl.Int64,
                              'anchor_year_group': pl.Utf8,
                              'dod': pl.Datetime},

            'icu/chartevents': {'subject_id': pl.Int64,
                                'hadm_id': pl.Int64,
                                'stay_id': pl.Int64,
                                'itemid': pl.Int64,
                                'value': pl.Utf8,
                                'valuenum': pl.Float64,
                                'valueuom': pl.Categorical,
                                'warning': pl.Float64,
                                'charttime': pl.Datetime,
                                'storetime': pl.Datetime},

            'icu/d_items': {'itemid': pl.Int64,
                            'label': pl.Categorical,
                            'abbreviation': pl.Utf8,
                            'linksto': pl.Utf8,
                            'category': pl.Utf8,
                            'unitname': pl.Utf8,
                            'param_type': pl.Utf8,
                            'lownormalvalue': pl.Float64,
                            'highnormalvalue': pl.Float64},

            'icu/inputevents': {'subject_id': pl.Int64,
                                'hadm_id': pl.Int64,
                                'stay_id': pl.Int64,
                                'itemid': pl.Int64,
                                'amount': pl.Float64,
                                'amountuom': pl.Utf8,
                                'rate': pl.Float64,
                                'rateuom': pl.Utf8,
                                'orderid': pl.Int64,
                                'linkorderid': pl.Int64,
                                'ordercategoryname': pl.Utf8,
                                'secondaryordercategoryname': pl.Utf8,
                                'ordercomponenttypedescription': pl.Utf8,
                                'ordercategorydescription': pl.Utf8,
                                'patientweight': pl.Float64,
                                'totalamount': pl.Float64,
                                'totalamountuom': pl.Utf8,
                                'isopenbag': pl.Int64,
                                'continueinnextdept': pl.Int64,
                                'statusdescription': pl.Utf8,
                                'originalamount': pl.Float64,
                                'originalrate': pl.Float64,
                                'starttime': pl.Datetime,
                                'endtime': pl.Datetime,
                                'storetime': pl.Datetime},

            'cases': {'CaseID': pl.Int64,
                      'PatientID': pl.Int64,
                      'AdmissionYear': pl.Int64,
                      'TimeOfStay': pl.Int64,
                      'ICUOffset': pl.Int64,
                      'saps3': pl.Int64,
                      'HospitalDischargeType': pl.Int64,
                      'DischargeState': pl.Int64,
                      'DischargeUnit': pl.Int64,
                      'OffsetOfDeath': pl.Int64,
                      'EstimatedSurvivalObservationTime': pl.Int64,
                      'Sex': pl.Int64,
                      'WeightOnAdmission': pl.Int64,
                      'HeightOnAdmission': pl.Int64,
                      'AgeOnAdmission': pl.Int64,
                      'HospitalUnit': pl.Int64,
                      'ReferringUnit': pl.Int64,
                      'ICD10Main': pl.Categorical,
                      'ICD10MainText': pl.Categorical,
                      'DiagnosisT2': pl.Categorical,
                      'SurgicalSite': pl.Int64,
                      'HoursOfCRRT': pl.Int64,
                      'AdmissionFormHasSepsis': pl.Int64,
                      'OrbisDataAvailable': pl.Int64,
                      'HeartSurgeryAdditionalData': pl.Int64,
                      'HeartSurgeryCPBTime': pl.Int64,
                      'HeartSurgeryCrossClampTime': pl.Int64,
                      'HeartSurgeryBeginOffset': pl.Int64,
                      'HeartSurgeryEndOffset': pl.Int64,
                      'OffsetAfterFirstAdmission': pl.Int64},

            'd_references': {'ReferenceGlobalID': pl.Int64,
                             'ReferenceValue': pl.Categorical,
                             'ReferenceName': pl.Categorical,
                             'ReferenceDescription': pl.Categorical,
                             'ReferenceUnit': pl.Categorical,
                             'ReferenceOrder': pl.Int64,
                             'ReferenceType': pl.Int64,
                             'Data': pl.Categorical},

            'laboratory': {'id': pl.Int64,
                           'CaseID': pl.Int64,
                           'LaboratoryID': pl.Int64,
                           'Offset': pl.Int64,
                           'LaboratoryValue': pl.Float64,
                           'LaboratoryType': pl.Int64},

            'medication': {'id': pl.Int64,
                           'CaseID': pl.Int64,
                           'PatientID': pl.Int64,
                           'DrugID': pl.Int64,
                           'Offset': pl.Int64,
                           'OffsetDrugEnd': pl.Int64,
                           'IsSingleDose': pl.Int64,
                           'Amount': pl.Float64,
                           'AmountPerMinute': pl.Float64,
                           'GivenState': pl.Int64}}
